name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: docker-compose -f ./tests/docker-compose.yaml up -d
      - name: Wait for CouchDB service
        run: until curl http://localhost:5984 > /dev/null 2>&1 ; do sleep 1; done
      - run: ./gradlew test
      - name: Collect Docker Compose logs
        if: failure()
        run: docker-compose -f ./tests/docker-compose.yaml logs || true
